-- Weltenschlacht journal, schema version 1 (one H2 database per Cow2Win guild).
-- Enums are stored as VARCHAR with the Java enum name. Statements are separated
-- by ";" at the end of a line; no ";" inside string literals (see SchemaMigrator).

-- Seasons live only in the journal. A season covers start_date <= day < end_date
-- (end_date is the first day after the season, so a gapless 12-week raster has
-- end_date = start_date of the next season).
CREATE TABLE season (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_number INT          NOT NULL,
    start_date    DATE         NOT NULL,
    end_date      DATE         NOT NULL,
    note          VARCHAR,
    CONSTRAINT uq_season_number UNIQUE (season_number),
    CONSTRAINT ck_season_dates CHECK (end_date > start_date)
);

-- The own guild (exactly one per database) and the opponents, identified by their game guild id.
CREATE TABLE guild (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_guild_id BIGINT       NOT NULL,
    name          VARCHAR      NOT NULL,
    server        INT          NOT NULL,
    is_own        BOOLEAN      NOT NULL,
    own_marker    BOOLEAN GENERATED ALWAYS AS (CASE WHEN is_own THEN TRUE END),
    CONSTRAINT uq_guild_game_id UNIQUE (game_guild_id),
    CONSTRAINT uq_guild_own UNIQUE (own_marker)
);

-- A player name exactly as in the log (raw text, case and spaces significant), per guild.
CREATE TABLE player (
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id INT     NOT NULL,
    name     VARCHAR NOT NULL,
    CONSTRAINT fk_player_guild FOREIGN KEY (guild_id) REFERENCES guild (id) ON DELETE CASCADE,
    CONSTRAINT uq_player_name UNIQUE (guild_id, name)
);

-- Optional link of an own-guild player to a Cow2Win guild member (by member id, never by name).
CREATE TABLE player_assignment (
    player_id    INT         NOT NULL PRIMARY KEY,
    member_id    VARCHAR,
    status       VARCHAR(20) NOT NULL,
    confirmed_at TIMESTAMP   NOT NULL,
    CONSTRAINT fk_assignment_player FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE CASCADE,
    CONSTRAINT ck_assignment_status CHECK (status IN ('ASSIGNED', 'NOT_IN_COW2WIN', 'FORMER', 'OPEN')),
    CONSTRAINT ck_assignment_member CHECK (status <> 'ASSIGNED' OR member_id IS NOT NULL)
);
CREATE INDEX ix_assignment_member ON player_assignment (member_id);

-- Manual mapping of an unknown name to a catalog id; name_key = GameNameNormalizer.key(raw_name).
CREATE TABLE name_mapping (
    kind       VARCHAR(20) NOT NULL,
    name_key   VARCHAR     NOT NULL,
    raw_name   VARCHAR     NOT NULL,
    catalog_id VARCHAR     NOT NULL,
    created_at TIMESTAMP   NOT NULL,
    CONSTRAINT pk_name_mapping PRIMARY KEY (kind, name_key),
    CONSTRAINT ck_name_mapping_kind CHECK (kind IN ('FORTIFICATION', 'HERO', 'PET', 'TITAN', 'TOTEM'))
);

-- One battle day against one opponent; head data from the most recently saved log.
CREATE TABLE battle (
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    battle_date       DATE        NOT NULL,
    own_guild_id      INT         NOT NULL,
    opponent_guild_id INT         NOT NULL,
    season_id         INT,
    ranking_points    INT,
    result            VARCHAR(10),
    status            VARCHAR(10) NOT NULL,
    created_at        TIMESTAMP   NOT NULL,
    updated_at        TIMESTAMP   NOT NULL,
    CONSTRAINT fk_battle_own_guild FOREIGN KEY (own_guild_id) REFERENCES guild (id),
    CONSTRAINT fk_battle_opponent FOREIGN KEY (opponent_guild_id) REFERENCES guild (id),
    CONSTRAINT fk_battle_season FOREIGN KEY (season_id) REFERENCES season (id) ON DELETE SET NULL,
    CONSTRAINT uq_battle UNIQUE (battle_date, opponent_guild_id),
    CONSTRAINT ck_battle_result CHECK (result IN ('WIN', 'LOSS', 'DRAW', 'RUNNING')),
    CONSTRAINT ck_battle_status CHECK (status IN ('RUNNING', 'FINISHED'))
);
CREATE INDEX ix_battle_date ON battle (battle_date);
CREATE INDEX ix_battle_season ON battle (season_id, battle_date);

-- At most one attack and one defense log per battle; a later export of the same direction replaces it.
-- The guild names/servers are kept as written in this log's file name; the ids are on battle/guild.
CREATE TABLE battle_log (
    id                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    battle_id              INT         NOT NULL,
    direction              VARCHAR(10) NOT NULL,
    language               VARCHAR(50) NOT NULL,
    file_name              VARCHAR     NOT NULL,
    own_guild_name         VARCHAR     NOT NULL,
    own_server             INT         NOT NULL,
    opponent_name          VARCHAR     NOT NULL,
    opponent_server        INT         NOT NULL,
    ranking_points_in_file INT         NOT NULL,
    result_in_file         VARCHAR(10),
    raw_csv                BLOB        NOT NULL,
    raw_size               INT         NOT NULL,
    sha256                 CHAR(64)    NOT NULL,
    parser_version         INT         NOT NULL,
    imported_at            TIMESTAMP   NOT NULL,
    points_total           INT         NOT NULL,
    CONSTRAINT fk_log_battle FOREIGN KEY (battle_id) REFERENCES battle (id) ON DELETE CASCADE,
    CONSTRAINT uq_log_direction UNIQUE (battle_id, direction),
    CONSTRAINT ck_log_direction CHECK (direction IN ('ATTACK', 'DEFENSE')),
    CONSTRAINT ck_log_result CHECK (result_in_file IN ('WIN', 'LOSS', 'DRAW', 'RUNNING'))
);

CREATE TABLE parse_problem (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    battle_log_id INT     NOT NULL,
    seq           INT     NOT NULL,
    line_number   INT     NOT NULL,
    line          VARCHAR NOT NULL,
    reason        VARCHAR NOT NULL,
    CONSTRAINT fk_problem_log FOREIGN KEY (battle_log_id) REFERENCES battle_log (id) ON DELETE CASCADE,
    CONSTRAINT uq_problem_seq UNIQUE (battle_log_id, seq)
);

-- seq: common file order of fort_event and fight within one log (BattleLog.entries()).
CREATE TABLE fort_event (
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    battle_log_id      INT         NOT NULL,
    seq                INT         NOT NULL,
    line_number        INT         NOT NULL,
    fortification_id   VARCHAR,
    fortification_name VARCHAR     NOT NULL,
    kind               VARCHAR(20) NOT NULL,
    free_positions     INT,
    total_positions    INT,
    text               VARCHAR     NOT NULL,
    points             INT         NOT NULL,
    CONSTRAINT fk_fort_event_log FOREIGN KEY (battle_log_id) REFERENCES battle_log (id) ON DELETE CASCADE,
    CONSTRAINT uq_fort_event_seq UNIQUE (battle_log_id, seq),
    CONSTRAINT ck_fort_event_kind CHECK (kind IN ('UNDEFENDED', 'CAPTURED'))
);

-- Player references deliberately without CASCADE: players are removed by the repository's cleanup.
CREATE TABLE fight (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    battle_log_id       INT         NOT NULL,
    seq                 INT         NOT NULL,
    line_number         INT         NOT NULL,
    fortification_id    VARCHAR,
    fortification_name  VARCHAR     NOT NULL,
    position            INT         NOT NULL,
    team_kind           VARCHAR(10),
    attacker_wins       BOOLEAN     NOT NULL,
    result_text         VARCHAR     NOT NULL,
    points              INT         NOT NULL,
    attacker_player_id  INT         NOT NULL,
    attacker_level      INT         NOT NULL,
    attacker_team_power INT         NOT NULL,
    defender_player_id  INT         NOT NULL,
    defender_level      INT         NOT NULL,
    defender_team_power INT         NOT NULL,
    buff_effect         VARCHAR(30),
    buff_percent        INT,
    buff_text           VARCHAR,
    CONSTRAINT fk_fight_log FOREIGN KEY (battle_log_id) REFERENCES battle_log (id) ON DELETE CASCADE,
    CONSTRAINT fk_fight_attacker FOREIGN KEY (attacker_player_id) REFERENCES player (id),
    CONSTRAINT fk_fight_defender FOREIGN KEY (defender_player_id) REFERENCES player (id),
    CONSTRAINT uq_fight_seq UNIQUE (battle_log_id, seq),
    CONSTRAINT ck_fight_team_kind CHECK (team_kind IN ('HERO', 'TITAN'))
);
CREATE INDEX ix_fight_attacker ON fight (attacker_player_id);
CREATE INDEX ix_fight_defender ON fight (defender_player_id);

CREATE TABLE fight_unit (
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fight_id           INT         NOT NULL,
    side               VARCHAR(10) NOT NULL,
    slot               INT         NOT NULL,
    kind               VARCHAR(10) NOT NULL,
    name               VARCHAR     NOT NULL,
    catalog_id         VARCHAR,
    totem_element      VARCHAR(20),
    color              VARCHAR(10),
    color_text         VARCHAR     NOT NULL,
    color_level        INT         NOT NULL,
    stars              INT         NOT NULL,
    level              INT         NOT NULL,
    power              INT,
    damage_dealt       INT         NOT NULL,
    damage_taken       INT         NOT NULL,
    healing            INT         NOT NULL,
    patronage_pet_id   VARCHAR,
    patronage_pet_name VARCHAR,
    patronage_power    INT,
    CONSTRAINT fk_unit_fight FOREIGN KEY (fight_id) REFERENCES fight (id) ON DELETE CASCADE,
    CONSTRAINT uq_unit_slot UNIQUE (fight_id, side, slot),
    CONSTRAINT ck_unit_side CHECK (side IN ('ATTACKER', 'DEFENDER')),
    CONSTRAINT ck_unit_kind CHECK (kind IN ('HERO', 'PET', 'TITAN', 'TOTEM'))
);
